apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
vars:
- name: domain
  objref:
    kind: ConfigMap
    name: cluster-vars
    apiVersion: v1
  fieldref:
    fieldpath: data.domain
configMapGenerator:
- envs:
  - params.env
  name: parameters
configurations:
- params.yaml